### ISSUE TITLE
FR: Disable debug logging

### ISSUE THREAD

**Issue by gerroon** [iOSonntag/obsidian-plugin-treefocus#1]
Hi
It would be great if you could disable console printing, it does kind of litter the console and makes it hard to deal with it, also probably a performance hit.

Thanks for the plugin, this is a great addition to Obsidian.

**Comment by iOSonntag** [comment]
Hi @gerroon,

can you tell me if you mean debug logs -> `[DEBUG][treefocus]: ...` 
or info logs `[INFO] [treefocus]: ...`

Because I thought I already disabled the debug logs via this code:

```ts
static debug(message: string, ...args: any[])
{
  if (Platform.isDesktopApp)
  {
    // in case it is unknown we assume production, even though it is not correct
    // it serves the purpose of not logging, when not in dev mode.

    if ((process?.env?.NODE_ENV ?? 'production') !== 'production')
    {
      console.log(`[DEBUG][${PluginInfo.pluginId}]: ${message}`, ...args);
    }
  }
}
```

**Comment by gerroon** [comment]
Hi

I see that it is in the dev console and it is triggered quite often

![image](https://github.com/iOSonntag/obsidian-plugin-treefocus/assets/8519469/7c30c55f-b8cb-4fa6-9f5c-013e93c030f9)


![image](https://github.com/iOSonntag/obsidian-plugin-treefocus/assets/8519469/995b5cd3-ea1c-4932-9ee2-5f8d76e6dfe9)

**Comment by iOSonntag** [comment]
K I guess then that I will disable debug logs completely and reactivate them if needed. Expect an update to arrive shortly.

Thanks for the Info

**Comment by iOSonntag** [comment]
Update is available, closing

**Comment by gerroon** [comment]
Hi

Thanks for the fix, would it be possible to disable INFO and EVENT as well given they have no use for a regular user. They are still enabled.

**Comment by iOSonntag** [comment]
I guess that makes sense. I disabled that logs as well
